version: 2
updates:
  - package-ecosystem: cargo
    directory: '/'
    schedule:
      interval: 'monthly'
      day: 'thursday'
      time: '02:00'
    open-pull-requests-limit: 10
    groups:
      aws:
        patterns: ["aws-*"]
      serde:
        patterns: ["serde", "serde*"]
      actix:
        patterns: ["actix*"]

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
