[package]
name = "svanill-vault-cli"
description = "A command line tool to access svanill-vault"
version = "0.1.0"
authors = ["Riccardo Attilio Galli <riccardo@sideralis.org>"]
edition = "2018"
repository = "https://github.com/svanill/svanill-vault-cli"
license = "AGPL-3.0-or-later"
readme = "README.md"

[dependencies]
svanill-vault-openapi = { path = "../svanill-vault-openapi", version = "0.1" }
structopt = "0.3.26"
atty = "0.2.14"
anyhow = "1.0.58"
thiserror = "1.0.31"
reqwest = { version = "0.11.9", default-features = false, features=["blocking", "gzip", "json", "rustls-tls", "rustls-tls-webpki-roots"] }
serde = { version = "1.0.138", features = ["derive"] }
serde_json = "1.0.55"
confy = "0.4.0"
rand = "0.8.5"
md-5 = "0.10.1"
mockito = "0.31.0"
assert_cmd = "2.0.4"
