[package]
name = "svanill-store"
version = "0.1.0"
authors = ["Riccardo Attilio Galli <riccardo@sideralis.org>"]
edition = "2018"
repository = "https://github.com/svanill/svanill-store-cli"
license = "AGPL-3.0-or-later"
readme = "README.md"

[dependencies]
structopt = "0.3.14"
atty = "0.2.14"
anyhow = "1.0.31"
thiserror = "1.0.19"
