[package]
name = "svanill-vault-server"
version = "0.1.0"
authors = ["Riccardo Attilio Galli <riccardo@sideralis.org>"]
repository = "https://github.com/svanill/svanill-vault-server"
edition = "2018"
license = "AGPL-3.0-or-later"
readme = "README.md"

[dependencies]
actix-web = "2.0.0"
actix-rt = "1.1.1"
env_logger = "0.7.1"
structopt = "0.3.15"
diesel = { version = "1.4.5", features = ["sqlite", "r2d2"] }
