[package]
name = "svanill-vault-server"
description = "svanill-vault, the server"
version = "0.6.2"
authors = ["Riccardo Attilio Galli <riccardo@sideralis.org>"]
repository = "https://github.com/svanill/svanill-vault-server"
edition = "2021"
license = "AGPL-3.0-or-later"
readme = "README.md"

[dependencies]
svanill-vault-openapi = { path = "../svanill-vault-openapi", version = "0.1" }
actix-web = { version = "4.2.1", features = ["rustls"] }
actix-http = "3.3.0"
actix-cors = "0.6.4"
actix-web-httpauth = "0.8.0"
env_logger = "0.10.0"
structopt = "0.3.26"
diesel = { version = "2.0.3", features = ["sqlite", "r2d2"] }
diesel_migrations = "2.0.0"
libsqlite3-sys = { version = "0.25.2", features = ["bundled"] }
serde = "1.0.152"
serde_json = "1.0.93"
serde_derive = "1.0.130"
thiserror = "1.0.37"
ring = "0.16.20"
hex = "0.4.3"
lru-cache = "0.1.2"
futures = "0.3.25"
anyhow = "1.0.69"
log = "0.4.17"
base64 = "0.20.0"
hmac = "0.12.1"
sha2 = "0.10.6"
color-backtrace = "0.5.1"
reqwest = { version = "0.11.13", default-features = false, features = ["blocking", "gzip", "multipart", "json", "rustls-tls", "rustls-tls-webpki-roots"] }
hyper = { version = "0.14.23", features = ["full"] }
hyper-rustls = { version = "0.23.2", features = ["webpki-roots", "http2"] }
sentry-actix = "0.29.1"
async-trait = "0.1.64"
aws-config = "0.54.1"
aws-credential-types = "0.54.1"
aws-sigv4 = "0.54.1"
aws-types = "0.54.1"
aws-sdk-s3 = "0.24.0"
aws-smithy-client = "0.54.1"
aws-smithy-types = "0.54.4"
http = "0.2.8"

[dependencies.sentry]
version = "0.30.0"
default-features = false
features = ["rustls", "backtrace", "contexts", "panic", "reqwest", "tracing"]

[dev-dependencies]
aws-smithy-client = { version = "0.54.1", features = ["test-util"] }
aws-smithy-http = "0.54.1"
aws-sdk-iam = "0.24.0"
tokio = "1.25.0"
ctor = "0.1.26"
actix-rt = "2.8.0"

[profile.release]
debug = true
