[package]
name = "svanill-vault-server"
description = "svanill-vault, the server"
version = "0.4.0"
authors = ["Riccardo Attilio Galli <riccardo@sideralis.org>"]
repository = "https://github.com/svanill/svanill-vault-server"
edition = "2018"
license = "AGPL-3.0-or-later"
readme = "README.md"

[dependencies]
svanill-vault-openapi = { path = "../svanill-vault-openapi", version = "0.1" }
actix-web = { version = "4.0.0-beta.10", features = ["rustls"] }
env_logger = "0.7.1"
structopt = "0.3.25"
diesel = { version = "1.4.8", features = ["sqlite", "r2d2"] }
libsqlite3-sys = { version = "0.18.0", features = ["bundled"] }
serde = "1.0.130"
serde_json = "1.0.69"
serde_derive = "1.0.130"
actix-http = "3.0.0-beta.11"
thiserror = "1.0.30"
ring = "0.16.20"
hex = "0.4.3"
lru-cache = "0.1.2"
rusoto_core = { version = "0.47.0", default-features = false, features = ["rustls", "rustls-webpki"] }
rusoto_s3 = { version = "0.47.0", default-features = false, features = ["rustls"] }
rusoto_credential = "0.47.0"
rusoto_signature = "0.47.0"
futures = "0.3.17"
anyhow = "1.0.45"
actix-web-httpauth = "0.6.0-beta.3"
log = "0.4.14"
actix-cors = "0.6.0-beta.3"
base64 = "0.12.3"
hmac = "0.7.1"
sha2 = "0.8.2"
time = "0.2.27"
chrono = "0.4.19"
color-backtrace = "0.4.2"
diesel_migrations = "1.4.0"
reqwest = { version = "0.11.6", default-features = false, features = ["blocking", "gzip", "multipart", "json", "rustls-tls", "rustls-tls-webpki-roots"] }
hyper = { version = "0.14.14", features = ["full"] }
hyper-rustls = { version = "0.22.1", features = ["webpki-roots"] }

[dependencies.sentry]
version = "0.23.0"
default-features = false
features = ["rustls", "backtrace", "contexts", "panic", "reqwest"]

[dev-dependencies]
tokio = "1.13.0"
ctor = "0.1.21"
rusoto_mock = { version = "0.47.0", default-features = false, features = ["rustls"] }
actix-rt = "2.4.0"
