[package]
name = "svanill-vault-server"
description = "svanill-vault, the server"
version = "0.6.1"
authors = ["Riccardo Attilio Galli <riccardo@sideralis.org>"]
repository = "https://github.com/svanill/svanill-vault-server"
edition = "2021"
license = "AGPL-3.0-or-later"
readme = "README.md"

[dependencies]
svanill-vault-openapi = { path = "../svanill-vault-openapi", version = "0.1" }
actix-web = { version = "4.1.0", features = ["rustls"] }
actix-http = "3.2.1"
actix-cors = "0.6.2"
actix-web-httpauth = "0.8.0"
env_logger = "0.9.0"
structopt = "0.3.26"
diesel = { version = "1.4.8", features = ["sqlite", "r2d2"] }
libsqlite3-sys = { version = "0.18.0", features = ["bundled"] }
serde = "1.0.144"
serde_json = "1.0.85"
serde_derive = "1.0.130"
thiserror = "1.0.33"
ring = "0.16.20"
hex = "0.4.3"
lru-cache = "0.1.2"
futures = "0.3.24"
anyhow = "1.0.63"
log = "0.4.17"
base64 = "0.13.0"
hmac = "0.12.1"
sha2 = "0.10.3"
color-backtrace = "0.5.1"
diesel_migrations = "1.4.0"
reqwest = { version = "0.11.9", default-features = false, features = ["blocking", "gzip", "multipart", "json", "rustls-tls", "rustls-tls-webpki-roots"] }
hyper = { version = "0.14.20", features = ["full"] }
hyper-rustls = { version = "0.23.0", features = ["webpki-roots", "http2"] }
sentry-actix = "0.27.0"
async-trait = "0.1.57"
aws-config = "0.47.0"
aws-sigv4 = "0.47.0"
aws-types = "0.47.0"
aws-sdk-s3 = "0.17.0"
aws-smithy-client = "0.47.0"
aws-smithy-types = "0.47.0"
http = "0.2.8"

[dependencies.sentry]
version = "0.27.0"
default-features = false
features = ["rustls", "backtrace", "contexts", "panic", "reqwest", "tracing"]

[dev-dependencies]
aws-smithy-client = { version = "0.47.0", features = ["test-util"] }
aws-smithy-http = "0.47.0"
aws-sdk-iam = "0.18.0"
tokio = "1.13.1"
ctor = "0.1.23"
actix-rt = "2.7.0"

[profile.release]
debug = true
