[package]
name = "svanill-vault-server"
version = "0.1.0"
authors = ["Riccardo Attilio Galli <riccardo@sideralis.org>"]
repository = "https://github.com/svanill/svanill-vault-server"
edition = "2018"
license = "AGPL-3.0-or-later"
readme = "README.md"

[dependencies]
svanill-vault-openapi = { path = "../svanill-vault-openapi", version = "0.1" }
actix-web = { version = "3.0.2", features = ["rustls"] }
env_logger = "0.7.1"
structopt = "0.3.15"
diesel = { version = "1.4.5", features = ["sqlite", "r2d2"] }
libsqlite3-sys = { version = ">=0.8.0, <0.19.0", features = ["bundled"] }
serde = "1.0.114"
serde_json = "1.0.56"
serde_derive = "1.0.114"
actix-http = "2.0.0"
thiserror = "1.0.20"
ring = "0.16.15"
hex = "0.4.2"
lru-cache = "0.1.2"
rusoto_core = { version = "0.45.0", default-features = false, features = ["rustls"] }
rusoto_s3 = { version = "0.45.0", default-features = false, features = ["rustls"] }
rusoto_credential = "0.45.0"
futures = "0.3.5"
anyhow = "1.0.31"
actix-web-httpauth = "0.5.0"
log = "0.4.8"
actix-cors = "0.3.0"
base64 = "0.12.3"
hmac = "0.7.1"
sha2 = "0.8.2"
time = "0.2.16"
rusoto_signature = "0.45.0"
chrono = "0.4.13"
color-backtrace = { version = "0.4.2" }
diesel_migrations = "1.4.0"
reqwest = { version = "0.10.7", default-features = false, features=["json", "rustls-tls"] }

[dependencies.sentry]
version = "0.20.1"
default-features = false
features = ["rustls", "backtrace", "contexts", "panic", "reqwest"]

[dev-dependencies]
tokio = "0.2.22"
ctor = "0.1.15"
rusoto_mock = { version = "0.45.0", default-features = false, features = ["rustls"] }
actix-rt = "1.1.1"
