[package]
name = "svanill-vault-server"
version = "0.1.0"
authors = ["Riccardo Attilio Galli <riccardo@sideralis.org>"]
repository = "https://github.com/svanill/svanill-vault-server"
edition = "2018"
license = "AGPL-3.0-or-later"
readme = "README.md"

[dependencies]
actix-web = "2.0.0"
actix-rt = "1.1.1"
env_logger = "0.7.1"
structopt = "0.3.15"
diesel = { version = "1.4.5", features = ["sqlite", "r2d2"] }
serde = "1.0.114"
serde_json = "1.0.56"
serde_derive = "1.0.114"
actix-http = "1.0.1"
thiserror = "1.0.20"
ring = "0.16.15"
hex = "0.4.2"
lru-cache = "0.1.2"
rusoto_core = "0.44.0"
rusoto_s3 = "0.44.0"
rusoto_credential = "0.44.0"
futures = "0.3.5"
anyhow = "1.0.31"
actix-web-httpauth = "0.4.2"
log = "0.4.8"
actix-cors = "0.2.0"
