name: Continuous integration

on:
  pull_request:
    branches-ignore:
      - release
  push:
    branches:
      - master

jobs:
  build-and-test:
    name: build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - uses: actions-rs/toolchain@v1
        with:
          profile: default # contains rustfmt, clippy
          toolchain: nightly

      - name: Setup cache (and restore immediately if there's a key match)
        uses: actions/cache@v2
        with:
          path: |
            target
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git
          # don't use Cargo.lock hash in the key, so we can change it
          # and still reuse most deps
          key: ${{ runner.os }}-build

      - name: cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build

      - name: Check that we didn't introduce native ssl
        run: "! ldd ../target/debug/svanill-vault-cli | grep -q libssl"

      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
          toolchain: nightly

      - name: cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets --all-features
          toolchain: nightly
